server:
  port: 9030
spring:
  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        hostname: order
        register-health-check: false
        ip-address: 127.0.0.1
        prefer-ip-address: true
    loadbalancer:
      retry:
        enabled: true
  application:
    name: order