server:
  port: 9030
spring:
  cloud:
    consul:
      host: 39.98.179.73
      discovery:
        hostname: order
        register-health-check: false
        ip-address: 119.27.163.171
        prefer-ip-address: true
    loadbalancer:
      retry:
        enabled: true
  application:
    name: order